name: client-tests-workflow

on:
  pull_request

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: install packages and run tests
        run: npm i && npm test